version: '2'
services:
  elasticsearch1:
    image: elasticsearch:5.0.1
    container_name: es1
    environment:
      - node.name=node1
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ~/work/docker/elasticsearch/config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch:5.0.1
    container_name: es2
    environment:
      - node.name=node2
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    networks:
      - esnet
    volumes:
      - ~/work/docker/elasticsearch/config:/usr/share/elasticsearch/config
  kibana:
    image: kibana:5.0.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch1:9200
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
